package:
  name: obc
  version: 0.1

source:
  path: .

requirements:
  run:
    - _r-mutex ==1.0.1
    - bwidget ==1.9.13
    - bzip2 ==1.0.8
    - ca-certificates ==2019.9.11
    - cairo ==1.16.0
    - cctools ==895
    - certifi ==2019.9.11
    - clang ==4.0.1
    - clang_osx-64 ==4.0.1
    - clangxx ==4.0.1
    - clangxx_osx-64 ==4.0.1
    - compiler-rt ==4.0.1
    - curl ==7.65.3
    - fontconfig ==2.13.1
    - freetype ==2.10.0
    - gettext ==0.19.8.1
    - gfortran_osx-64 ==4.8.5
    - glib ==2.58.3
    - graphite2 ==1.3.13
    - gsl ==2.5
    - harfbuzz ==2.4.0
    - icu ==58.2
    - jpeg ==9c
    - krb5 ==1.16.3
    - ld64 ==274.2
    - libblas ==3.8.0
    - libcblas ==3.8.0
    - libcurl ==7.65.3
    - libcxx ==4.0.1
    - libcxxabi ==4.0.1
    - libedit ==3.1.20170329
    - libffi ==3.2.1
    - libgfortran ==3.0.1
    - libiconv ==1.15
    - libopenblas ==0.3.7
    - libpng ==1.6.37
    - libssh2 ==1.8.2
    - libtiff ==4.0.9
    - libxml2 ==2.9.9
    - llvm ==4.0.1
    - llvm-lto-tapi ==4.0.1
    - llvm-openmp ==9.0.0
    - make ==4.2.1
    - ncurses ==6.1
    - openssl ==1.1.1d
    - pango ==1.40.14
    - pcre ==8.41
    - perl ==5.20.3.1
    - pip ==19.3.1
    - pixman ==0.38.0
    - python ==3.6.8
    - r-ape ==5.1
    - r-assertthat ==0.2.1
    - r-backports ==1.1.5
    - r-base ==3.5.1
    - r-bh ==1.69.0_1
    - r-bindr ==0.1.1
    - r-bindrcpp ==0.2.2
    - r-bitops ==1.0_6
    - r-boot ==1.3_23
    - r-cli ==1.1.0
    - r-colorspace ==1.4_1
    - r-cowplot ==0.9.4
    - r-crayon ==1.3.4
    - r-data.table ==1.11.4
    - r-desctools ==0.99.28
    - r-digest ==0.6.21
    - r-dplyr ==0.7.6
    - r-ellipsis ==0.3.0
    - r-expm ==0.999_4
    - r-fansi ==0.4.0
    - r-foreign ==0.8_72
    - r-getopt ==1.20.3
    - r-ggalluvial ==0.9.1
    - r-ggplot2 ==3.0.0
    - r-ggpubr ==0.2
    - r-ggrepel ==0.8.1
    - r-ggsci ==2.9
    - r-ggsignif ==0.6.0
    - r-glue ==1.3.1
    - r-gridextra ==2.3
    - r-gtable ==0.3.0
    - r-labeling ==0.3
    - r-lattice ==0.20_38
    - r-lazyeval ==0.2.2
    - r-magrittr ==1.5
    - r-manipulate ==1.0.1
    - r-mass ==7.3_51.4
    - r-matrix ==1.2_17
    - r-mgcv ==1.8_29
    - r-munsell ==0.5.0
    - r-mvtnorm ==1.0_11
    - r-nlme ==3.1_141
    - r-optparse ==1.6.1
    - r-pillar ==1.4.2
    - r-pkgconfig ==2.0.3
    - r-plogr ==0.2.0
    - r-plyr ==1.8.4
    - r-polynom ==1.4_0
    - r-purrr ==0.3.3
    - r-r6 ==2.4.0
    - r-rcolorbrewer ==1.1_2
    - r-rcpp ==1.0.2
    - r-rcurl ==1.95_4.11
    - r-reshape2 ==1.4.3
    - r-rlang ==0.4.1
    - r-scales ==1.0.0
    - r-stringi ==1.4.3
    - r-stringr ==1.4.0
    - r-tibble ==2.1.3
    - r-tidyr ==0.8.3
    - r-tidyselect ==0.2.5
    - r-utf8 ==1.1.4
    - r-vctrs ==0.2.0
    - r-viridislite ==0.3.0
    - r-withr ==2.1.2
    - r-zeallot ==0.1.0
    - readline ==7.0
    - setuptools ==41.6.0
    - sqlite ==3.28.0
    - tk ==8.6.9
    - tktable ==2.10
    - wheel ==0.33.6
    - xz ==5.2.4
    - zlib ==1.2.11
  host:
    - python ==3.6.8
    - setuptools ==41.6.0
    - perl ==5.20.3.1
    - r-base ==3.5.1

test:
  commands:
    - radarplot -h
