package:
  name: obc
  version: 0.1

source:
  path: .


requirements:
  run:
    - _r-mutex
    - bwidget
    - bzip2
    - ca-certificates
    - cairo
    - cctools
    - certifi
    - clang
    - clang_osx-64
    - clangxx
    - clangxx_osx-64
    - compiler-rt
    - curl
    - fontconfig
    - freetype
    - fribidi
    - gettext
    - gfortran_impl_osx-64
    - gfortran_osx-64
    - glib
    - gmp
    - graphite2
    - gsl
    - harfbuzz
    - icu
    - isl
    - jpeg
    - krb5
    - ld64
    - libblas
    - libcblas
    - libcurl
    - libcxx
    - libedit
    - libffi
    - libgfortran
    - libiconv
    - liblapack
    - libllvm9
    - libopenblas
    - libpng
    - libssh2
    - libtiff
    - libxml2
    - llvm-openmp
    - lz4-c
    - make
    - mpc
    - mpfr
    - ncurses
    - openssl
    - pango
    - pcre
    - perl
    - pip
    - pixman
    - python
    - r-ape
    - r-assertthat
    - r-backports
    - r-base
    - r-bh
    - r-bitops
    - r-boot
    - r-cli
    - r-colorspace
    - r-cowplot
    - r-crayon
    - r-data.table
    - r-desctools
    - r-digest
    - r-dplyr
    - r-ellipsis
    - r-expm
    - r-fansi
    - r-foreign
    - r-getopt
    - r-ggalluvial
    - r-ggplot2
    - r-ggpubr
    - r-ggrepel
    - r-ggsci
    - r-ggsignif
    - r-glue
    - r-gridextra
    - r-gtable
    - r-labeling
    - r-lattice
    - r-lazyeval
    - r-lifecycle
    - r-magrittr
    - r-manipulate
    - r-mass
    - r-matrix
    - r-mgcv
    - r-munsell
    - r-mvtnorm
    - r-nlme
    - r-optparse
    - r-pillar
    - r-pkgconfig
    - r-plogr
    - r-plyr
    - r-polynom
    - r-purrr
    - r-r6
    - r-rcolorbrewer
    - r-rcpp
    - r-rcurl
    - r-reshape2
    - r-rlang
    - r-scales
    - r-stringi
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-utf8
    - r-vctrs
    - r-viridis
    - r-viridislite
    - r-withr
    - r-zeallot
    - readline
    - setuptools
    - sqlite
    - tapi
    - tk
    - tktable
    - wheel
    - xz
    - zlib
    - zstd
  host:
    - python
    - setuptools
    - perl
    - r-base

test:
  commands:
    - radarplot -h
